### Import Data and Required Packages

In [50]:
%pip install nltk

import nltk
from nltk.stem import PorterStemmer
import numpy as np 
import pandas as pd

Requirement already satisfied: nltk in c:\Users\dakid\Downloads\Projects\CineMatch\venv\Lib\site-packages (3.9.3)
Requirement already satisfied: click in c:\Users\dakid\Downloads\Projects\CineMatch\venv\Lib\site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in c:\Users\dakid\Downloads\Projects\CineMatch\venv\Lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in c:\Users\dakid\Downloads\Projects\CineMatch\venv\Lib\site-packages (from nltk) (2026.2.28)
Requirement already satisfied: tqdm in c:\Users\dakid\Downloads\Projects\CineMatch\venv\Lib\site-packages (from nltk) (4.67.3)
Requirement already satisfied: colorama in c:\Users\dakid\Downloads\Projects\CineMatch\venv\Lib\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

### Import the CSV Data as Pandas DataFrame

In [51]:
df = pd.read_csv('../data/TMDB_top25k.csv')

In [52]:
df.head(2)

,movie_id,title,overview,genres,keywords,cast,crew,original_language,vote_average,production_countries
0,157336,Interstellar,The adventures of a group of explorers who mak...,"['Adventure', 'Drama', 'ScienceFiction']","['rescue', 'future', 'spacecraft', 'raceagains...","['MatthewMcConaughey', 'AnneHathaway', 'Michae...",['ChristopherNolan'],en,8.50,"United Kingdom, United States of America"
1,27205,Inception,"Cobb, a skilled thief who commits corporate es...","['Action', 'ScienceFiction', 'Adventure']","['mission', 'dreams', 'kidnapping', 'spy', 'al...","['LeonardoDiCaprio', 'JosephGordon-Levitt', 'K...",['ChristopherNolan'],en,8.37,"United Kingdom, United States of America"

In [53]:
print(df.columns)

Index(['movie_id', 'title', 'overview', 'genres', 'keywords', 'cast', 'crew',
       'original_language', 'vote_average', 'production_countries'],
      dtype='str')

In [54]:
movies = df[['movie_id', 'title', 'overview', 'genres', 'keywords', 'cast', 'crew', 'original_language', 'vote_average']]

In [55]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,original_language,vote_average
0,157336,Interstellar,The adventures of a group of explorers who mak...,"['Adventure', 'Drama', 'ScienceFiction']","['rescue', 'future', 'spacecraft', 'raceagains...","['MatthewMcConaughey', 'AnneHathaway', 'Michae...",['ChristopherNolan'],en,8.500
1,27205,Inception,"Cobb, a skilled thief who commits corporate es...","['Action', 'ScienceFiction', 'Adventure']","['mission', 'dreams', 'kidnapping', 'spy', 'al...","['LeonardoDiCaprio', 'JosephGordon-Levitt', 'K...",['ChristopherNolan'],en,8.370
2,24428,The Avengers,When an unexpected enemy emerges and threatens...,"['ScienceFiction', 'Action', 'Adventure']","['newyorkcity', 'superhero', 'shield', 'basedo...","['RobertDowneyJr.', 'ChrisEvans', 'MarkRuffalo']",['JossWhedon'],en,7.942
3,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,"['Action', 'Crime', 'Thriller']","['sadism', 'chaos', 'secretidentity', 'crimefi...","['ChristianBale', 'HeathLedger', 'AaronEckhart']",['ChristopherNolan'],en,8.526
4,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","['Action', 'Adventure', 'Fantasy', 'ScienceFic...","['paraplegic', 'attachmenttonature', 'culturec...","['SamWorthington', 'ZoeSaldaña', 'SigourneyWea...",['JamesCameron'],en,7.600

### Coverting all columns into list

In [56]:
import ast

def convert_to_list(text):
    try:
        return ast.literal_eval(text)
    except:
        return []

movies['genres'] = movies['genres'].apply(convert_to_list)
movies['keywords'] = movies['keywords'].apply(convert_to_list)
movies['cast'] = movies['cast'].apply(convert_to_list)
movies['crew'] = movies['crew'].apply(convert_to_list)

print("✅ Done")

✅ Done

In [57]:
movies['keywords'] = movies['keywords'].apply(lambda x: x[0:5])
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,original_language,vote_average
0,157336,Interstellar,The adventures of a group of explorers who mak...,"[Adventure, Drama, ScienceFiction]","[rescue, future, spacecraft, raceagainsttime, ...","[MatthewMcConaughey, AnneHathaway, MichaelCaine]",[ChristopherNolan],en,8.500
1,27205,Inception,"Cobb, a skilled thief who commits corporate es...","[Action, ScienceFiction, Adventure]","[mission, dreams, kidnapping, spy, allegory]","[LeonardoDiCaprio, JosephGordon-Levitt, KenWat...",[ChristopherNolan],en,8.370
2,24428,The Avengers,When an unexpected enemy emerges and threatens...,"[ScienceFiction, Action, Adventure]","[newyorkcity, superhero, shield, basedoncomic,...","[RobertDowneyJr., ChrisEvans, MarkRuffalo]",[JossWhedon],en,7.942
3,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,"[Action, Crime, Thriller]","[sadism, chaos, secretidentity, crimefighter, ...","[ChristianBale, HeathLedger, AaronEckhart]",[ChristopherNolan],en,8.526
4,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, ScienceFiction]","[paraplegic, attachmenttonature, cultureclash,...","[SamWorthington, ZoeSaldaña, SigourneyWeaver]",[JamesCameron],en,7.600

In [58]:
movies.iloc[0]['keywords']

['rescue',
 'future',
 'spacecraft',
 'raceagainsttime',
 'artificialintelligence(a.i.)']

In [59]:
movies.shape

(25000, 9)

### Check Missing values

In [60]:
movies.isnull().sum()

movie_id              0
title                 0
overview             28
genres                0
keywords              0
cast                  0
crew                  0
original_language     0
vote_average          0
dtype: int64

In [61]:
movies.dropna(inplace=True)
movies.reset_index(drop=True, inplace=True)

In [62]:
movies.shape

(24972, 9)

In [63]:
movies.isnull().sum()

movie_id             0
title                0
overview             0
genres               0
keywords             0
cast                 0
crew                 0
original_language    0
vote_average         0
dtype: int64

### Check data types

In [64]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 24972 entries, 0 to 24971
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   movie_id           24972 non-null  int64
 1   title              24972 non-null  str
 2   overview           24972 non-null  str
 3   genres             24972 non-null  object
 4   keywords           24972 non-null  object
 5   cast               24972 non-null  object
 6   crew               24972 non-null  object
 7   original_language  24972 non-null  str
 8   vote_average       24972 non-null  float64
dtypes: float64(1), int64(1), object(4), str(3)
memory usage: 1.7+ MB

### handle overview (converting to list)

In [65]:
movies.iloc[0]['overview']

'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.'

In [66]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())
movies.sample(4)

,movie_id,title,overview,genres,keywords,cast,crew,original_language,vote_average
21618,227933,Alemao,"[Five, undercover, cops, at, Complexo, do, Ale...","[Action, Drama, Crime]",[],"[CaioBlat, GabrielBragaNunes, MarceloMelloJr.]",[JoséEduardoBelmonte],en,6.2
21323,13957,Closing the Ring,"[During, the, 1940s,, a, group, of, young, men...","[Drama, Romance]","[airplane, worldwarii, bomber, love, soldier]","[ShirleyMacLaine, ChristopherPlummer, MischaBa...",[RichardAttenborough],en,6.1
18663,150273,The Return,"[Two, young, children, and, an, adult, in, a, ...","[Mystery, Thriller, ScienceFiction]","[sheriff, alien, alienabduction, cattlemutilat...","[Jan-MichaelVincent, CybillShepherd, MartinLan...",[GreydonClark],en,5.9
11463,29452,The Face of Another,"[A, businessman, with, a, disfigured, face, ob...","[Drama, ScienceFiction]","[mask, japan, dualidentity, basedonnovelorbook...","[TatsuyaNakadai, MikijiroHira, MachikoKyō]",[HiroshiTeshigahara],ja,7.8

In [67]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 24972 entries, 0 to 24971
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   movie_id           24972 non-null  int64
 1   title              24972 non-null  str
 2   overview           24972 non-null  object
 3   genres             24972 non-null  object
 4   keywords           24972 non-null  object
 5   cast               24972 non-null  object
 6   crew               24972 non-null  object
 7   original_language  24972 non-null  str
 8   vote_average       24972 non-null  float64
dtypes: float64(1), int64(1), object(5), str(2)
memory usage: 1.7+ MB

### Concatinate all Columns

In [68]:
movies['tags'] = movies['overview'] + (movies['keywords'] * 4) + (movies['genres'] * 4) + (movies['cast'] * 3) + (movies['crew'] * 3)

In [69]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,original_language,vote_average,tags
0,157336,Interstellar,"[The, adventures, of, a, group, of, explorers,...","[Adventure, Drama, ScienceFiction]","[rescue, future, spacecraft, raceagainsttime, ...","[MatthewMcConaughey, AnneHathaway, MichaelCaine]",[ChristopherNolan],en,8.500,"[The, adventures, of, a, group, of, explorers,..."
1,27205,Inception,"[Cobb,, a, skilled, thief, who, commits, corpo...","[Action, ScienceFiction, Adventure]","[mission, dreams, kidnapping, spy, allegory]","[LeonardoDiCaprio, JosephGordon-Levitt, KenWat...",[ChristopherNolan],en,8.370,"[Cobb,, a, skilled, thief, who, commits, corpo..."
2,24428,The Avengers,"[When, an, unexpected, enemy, emerges, and, th...","[ScienceFiction, Action, Adventure]","[newyorkcity, superhero, shield, basedoncomic,...","[RobertDowneyJr., ChrisEvans, MarkRuffalo]",[JossWhedon],en,7.942,"[When, an, unexpected, enemy, emerges, and, th..."
3,155,The Dark Knight,"[Batman, raises, the, stakes, in, his, war, on...","[Action, Crime, Thriller]","[sadism, chaos, secretidentity, crimefighter, ...","[ChristianBale, HeathLedger, AaronEckhart]",[ChristopherNolan],en,8.526,"[Batman, raises, the, stakes, in, his, war, on..."
4,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[paraplegic, attachmenttonature, cultureclash,...","[SamWorthington, ZoeSaldaña, SigourneyWeaver]",[JamesCameron],en,7.600,"[In, the, 22nd, century,, a, paraplegic, Marin..."

In [70]:
movies.iloc[0]['tags']

['The',
 'adventures',
 'of',
 'a',
 'group',
 'of',
 'explorers',
 'who',
 'make',
 'use',
 'of',
 'a',
 'newly',
 'discovered',
 'wormhole',
 'to',
 'surpass',
 'the',
 'limitations',
 'on',
 'human',
 'space',
 'travel',
 'and',
 'conquer',
 'the',
 'vast',
 'distances',
 'involved',
 'in',
 'an',
 'interstellar',
 'voyage.',
 'rescue',
 'future',
 'spacecraft',
 'raceagainsttime',
 'artificialintelligence(a.i.)',
 'rescue',
 'future',
 'spacecraft',
 'raceagainsttime',
 'artificialintelligence(a.i.)',
 'rescue',
 'future',
 'spacecraft',
 'raceagainsttime',
 'artificialintelligence(a.i.)',
 'rescue',
 'future',
 'spacecraft',
 'raceagainsttime',
 'artificialintelligence(a.i.)',
 'Adventure',
 'Drama',
 'ScienceFiction',
 'Adventure',
 'Drama',
 'ScienceFiction',
 'Adventure',
 'Drama',
 'ScienceFiction',
 'Adventure',
 'Drama',
 'ScienceFiction',
 'MatthewMcConaughey',
 'AnneHathaway',
 'MichaelCaine',
 'MatthewMcConaughey',
 'AnneHathaway',
 'MichaelCaine',
 'MatthewMcConaughey',
 'AnneHathaway',
 'MichaelCaine',
 'ChristopherNolan',
 'ChristopherNolan',
 'ChristopherNolan']

### droping those extra columns

In [71]:
new_df = movies[['movie_id', 'title', 'tags', 'original_language', 'vote_average']]

In [72]:
new_df.head()

,movie_id,title,tags,original_language,vote_average
0,157336,Interstellar,"[The, adventures, of, a, group, of, explorers,...",en,8.500
1,27205,Inception,"[Cobb,, a, skilled, thief, who, commits, corpo...",en,8.370
2,24428,The Avengers,"[When, an, unexpected, enemy, emerges, and, th...",en,7.942
3,155,The Dark Knight,"[Batman, raises, the, stakes, in, his, war, on...",en,8.526
4,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...",en,7.600

### Converting list to str

In [73]:
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))
new_df.head()

,movie_id,title,tags,original_language,vote_average
0,157336,Interstellar,The adventures of a group of explorers who mak...,en,8.500
1,27205,Inception,"Cobb, a skilled thief who commits corporate es...",en,8.370
2,24428,The Avengers,When an unexpected enemy emerges and threatens...,en,7.942
3,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,en,8.526
4,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...",en,7.600

In [74]:
new_df.iloc[0]['tags']

'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage. rescue future spacecraft raceagainsttime artificialintelligence(a.i.) rescue future spacecraft raceagainsttime artificialintelligence(a.i.) rescue future spacecraft raceagainsttime artificialintelligence(a.i.) rescue future spacecraft raceagainsttime artificialintelligence(a.i.) Adventure Drama ScienceFiction Adventure Drama ScienceFiction Adventure Drama ScienceFiction Adventure Drama ScienceFiction MatthewMcConaughey AnneHathaway MichaelCaine MatthewMcConaughey AnneHathaway MichaelCaine MatthewMcConaughey AnneHathaway MichaelCaine ChristopherNolan ChristopherNolan ChristopherNolan'

### Converting to lower case

In [75]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [76]:
new_df.head()

,movie_id,title,tags,original_language,vote_average
0,157336,Interstellar,the adventures of a group of explorers who mak...,en,8.500
1,27205,Inception,"cobb, a skilled thief who commits corporate es...",en,8.370
2,24428,The Avengers,when an unexpected enemy emerges and threatens...,en,7.942
3,155,The Dark Knight,batman raises the stakes in his war on crime. ...,en,8.526
4,19995,Avatar,"in the 22nd century, a paraplegic marine is di...",en,7.600

In [77]:
new_df.iloc[0]['tags']

'the adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage. rescue future spacecraft raceagainsttime artificialintelligence(a.i.) rescue future spacecraft raceagainsttime artificialintelligence(a.i.) rescue future spacecraft raceagainsttime artificialintelligence(a.i.) rescue future spacecraft raceagainsttime artificialintelligence(a.i.) adventure drama sciencefiction adventure drama sciencefiction adventure drama sciencefiction adventure drama sciencefiction matthewmcconaughey annehathaway michaelcaine matthewmcconaughey annehathaway michaelcaine matthewmcconaughey annehathaway michaelcaine christophernolan christophernolan christophernolan'

### Word Stemming (Simplifying Words)
We use `PorterStemmer` to cut down words to their base root. 
For example, the words **'action'**, **'actions'**, and **'actionable'** all mean the exact same thing. But a computer might treat them as 3 completely different words.
Stemming cuts them all down to just **'action'**. This helps the model realize they mean the same thing and improves our movie recommendations!

In [78]:
from nltk.stem.porter import PorterStemmer   
ps = PorterStemmer()

In [79]:
def stems(text):
    T = []
    
    for i in text.split():
        T.append(ps.stem(i))
    
    return " ".join(T)

In [80]:
new_df['tags'] = new_df['tags'].apply(stems)

In [81]:
new_df.iloc[0]['tags']

'the adventur of a group of explor who make use of a newli discov wormhol to surpass the limit on human space travel and conquer the vast distanc involv in an interstellar voyage. rescu futur spacecraft raceagainsttim artificialintelligence(a.i.) rescu futur spacecraft raceagainsttim artificialintelligence(a.i.) rescu futur spacecraft raceagainsttim artificialintelligence(a.i.) rescu futur spacecraft raceagainsttim artificialintelligence(a.i.) adventur drama sciencefict adventur drama sciencefict adventur drama sciencefict adventur drama sciencefict matthewmcconaughey annehathaway michaelcain matthewmcconaughey annehathaway michaelcain matthewmcconaughey annehathaway michaelcain christophernolan christophernolan christophernolan'

### Vectorization: Converting Text to Numbers

In [82]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=15000,
    stop_words='english',
    ngram_range=(1, 2),   
    min_df=2,
    sublinear_tf=True     
)

In [83]:
vectors = tfidf.fit_transform(new_df['tags'])

In [84]:
vectors[0]

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 31 stored elements and shape (1, 15000)>

In [85]:
vectors.shape

(24972, 15000)

In [86]:
len(tfidf.get_feature_names_out())

15000

### Finding the Most Similar Movies (Cosine Similarity)

In [87]:
from sklearn.metrics.pairwise import cosine_similarity

In [88]:
similarity = cosine_similarity(vectors)
print(similarity)

[[1.         0.20308077 0.03530164 ... 0.00382361 0.02250723 0.00598856]
 [0.20308077 1.         0.04010071 ... 0.03603466 0.03733457 0.00537003]
 [0.03530164 0.04010071 1.         ... 0.02948085 0.04363772 0.        ]
 ...
 [0.00382361 0.03603466 0.02948085 ... 1.         0.05730514 0.0322558 ]
 [0.02250723 0.03733457 0.04363772 ... 0.05730514 1.         0.02338956]
 [0.00598856 0.00537003 0.         ... 0.0322558  0.02338956 1.        ]]

In [89]:
similarity.shape

(24972, 24972)

In [90]:
new_df[new_df['title'] == 'The Lego Movie'].index[0]

486

In [91]:
def recommend(movie):
    index = new_df[new_df['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:11]:
        print(new_df.iloc[i[0]].title)

In [92]:
recommend('Insidious')

Insidious: Chapter 2
Insidious: The Red Door
Insidious: Chapter 3
Insidious: The Last Key
The Medium
The Conjuring
The Vigil
The Toybox
Saw
Room for Rent

### Exporting the Model

In [93]:
import pickle
import scipy.sparse as sp

# Save movies dataframe
pickle.dump(new_df.to_dict(), open('../models/movie_dict.pkl', 'wb'))

# Save sparse vectors
sp.save_npz('../models/vectors.npz', vectors)